"""Data processing at the level of whole mechanisms."""

from . import io, net, reaction, species, util
from ._mech import (
    Mechanism,
    are_equivalent,
    combine_all,
    combine_enantiomers,
    consumption_mechanism,
    display,
    display_branching_fractions,
    display_reactions,
    display_species,
    drop_duplicate_reactions,
    drop_noncanonical_enantiomers,
    drop_reactions_by_smiles,
    drop_self_reactions,
    drop_unstable_product_reactions,
    enumerate_products,
    enumerate_reactions,
    expand_parent_stereo,
    expand_stereo,
    from_network,
    from_smiles,
    from_string,
    full_difference,
    left_update,
    merge_resonant_instabilities,
    merge_steps,
    neighborhood,
    network,
    reaction_amchis,
    reaction_count,
    reaction_difference,
    reaction_rate_objects,
    rename,
    rename_dict,
    replace_unstable_products,
    resonant_instability_reactions,
    resonant_unstable_species_names,
    species_count,
    species_difference,
    species_names,
    strict_unstable_species_names,
    string,
    unstable_species_names,
    update,
    with_comparison_rate_objects,
    with_fake_sort_data,
    with_index,
    with_key,
    with_rate_object_column,
    with_sort_data,
    with_sorted_reagents,
    with_species,
    without_reactions,
    without_sort_data,
    without_species,
    without_unused_species,
)

__all__ = [
    # types
    "Mechanism",
    # functions
    "from_network",
    "from_smiles",
    # properties
    "species_count",
    "reaction_count",
    "reaction_rate_objects",
    "reaction_amchis",
    "species_names",
    "unstable_species_names",
    "rename_dict",
    "network",
    "resonant_instability_reactions",
    "strict_unstable_species_names",
    "resonant_unstable_species_names",
    # add/remove reactions
    "drop_duplicate_reactions",
    "drop_unstable_product_reactions",
    "drop_self_reactions",
    "drop_reactions_by_smiles",
    "drop_noncanonical_enantiomers",
    # transformations
    "rename",
    "neighborhood",
    "with_species",
    "without_species",
    "without_reactions",
    "without_unused_species",
    "with_index",
    "with_key",
    "with_rate_object_column",
    "with_comparison_rate_objects",
    "expand_stereo",
    "consumption_mechanism",
    "combine_enantiomers",
    # binary operations
    "update",
    "left_update",
    "species_difference",
    "reaction_difference",
    "full_difference",
    "merge_steps",
    "merge_resonant_instabilities",
    # sequence operations
    "combine_all",
    # parent
    "expand_parent_stereo",
    # building
    "enumerate_reactions",
    "enumerate_products",
    "replace_unstable_products",
    # sorting
    "with_sort_data",
    "without_sort_data",
    "with_fake_sort_data",
    "with_sorted_reagents",
    # comparisons
    "are_equivalent",
    # read/write,
    "string",
    "from_string",
    # display
    "display",
    "display_species",
    "display_reactions",
    "display_branching_fractions",
    # modules
    "io",
    "util",
    "net",
    "reaction",
    "species",
]
