repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version (make sure this matches your pyproject.toml)
  rev: v0.12.1
  hooks:
    # Run the linter.
    - id: ruff-check
    # Run the formatter.
    - id: ruff-format
